### PR TITLE
Add a formatter plugin for sql files

### PR DESCRIPTION
**Pull request by pnezis**
After discussion on #2 , a formatter plugin for sql files. I will also add the sigil on a following commit

### CODE REVIEW

**Comment by pnezis** [comment]
Added the `~SQL` sigil, notice that we should handle differently single line sigils since `format` will produce not valid code.

**Comment by akoutmos** [comment]
Great work! I had a local branch going for adding the sigil...but you did all the hard work of adding tests too! Reviewing now and merging this in :D.

**Comment by pnezis** [comment]
Nice! Once you ship a new release I have some CI pipelines to change 😄

**Comment by akoutmos** [comment]
Made some minor changes post merging in and will prepare a new release shortly!

**Pull request merged**
